---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-exp
  labels:
    app: mongp-exp
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels: 
        app: mongo-exp
    spec: 
      containers:
       - name: mongo-exp
         image: mongo-express
         ports:
          - containerPort: 8081
         env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-password
          - name: ME_CONGIFG_MONGODB_SERVER
            valueFrom:
              secretKeyRef:
                name: mongo-configmap
                key: database_url


---
apiVersion: v1
kind: Service
metadata: 
  name: mongo-exp-ser
spec:
  selector:
    app: mongo-exp
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8081
     targetPort: 8081
     nodePort: 30000
